name: Module Katalon tests

on:
  workflow_dispatch:
    inputs:
      katalonRepo:
        description: 'Katalon tests repository'
        required: false
        type: string
        default: 'VirtoCommerce/vc-quality-gate-katalon'
      katalonRepoBranch:
        description: 'Katalon tests repository branch'
        required: false
        type: string
        default: 'dev'
      testSuite:
        description: "Test Suite"
        required: false
        type: string
        default: 'Test Suites/Modules/Platform_collection'
      installModules:
        description: 'Enable or disable "Install Modules" step'
        required: false
        type: boolean
        default: true
      installCustomModule:
        description: 'Boolean param. true - to install custom module ver.'
        required: false
        type: boolean
        default: true
      customModuleId:
        description: 'Custom Module id'
        required: false
        type: string
        default: 'VirtoCommerce.ExperienceApi'
      customModuleUrl:
        description: 'Custom module Module url'
        required: false
        type: string
        default: ''

jobs:
  module-katalon-tests:
    uses: VirtoCommerce/.github/.github/workflows/e2e.yml@main
    with:
      katalonRepo: ${{ inputs.katalonRepo }}
      katalonRepoBranch: ${{ inputs.katalonRepoBranch }}
      testSuite: ${{ inputs.testSuite }}
      installModules: ${{ inputs.installModules }}
      installCustomModule: ${{ inputs.installCustomModule }}
      customModuleId: ${{ inputs.customModuleId }}
      customModuleUrl: ${{ inputs.customModuleUrl }}
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
      katalonApiKey: ${{ secrets.KATALON_API_KEY }}


