name: Experience API Integration tests(postman)

on:
 workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-18.04 # katalon action runs correctly on ubuntu-18.04
    env:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up .net Core 5.0.x for vc-build #GitHib Actions migrates to .net Core 5.x. To vc-build work properly need to manually install .net Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install VirtoCommerce.GlobalTool
      uses: VirtoCommerce/vc-github-actions/setup-vcbuild@master

    - name: Get Image Version
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: image

    # Temporary commented for speedup workflow test
    - name: Build
      run: vc-build Compile

    - name: Packaging
      run: vc-build Compress -skip Clean+Restore+Compile+Test

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Env
      uses: VirtoCommerce/vc-github-actions/docker-env@master
      with:
        githubUser: ${{ env.GITHUB_ACTOR }}
        githubToken: ${{ env.GITHUB_TOKEN }}
        platformDockerTag: 'dev-linux-latest'
        storefrontDockerTag: 'dev-linux-latest'
        platformImage: ghcr.io/virtocommerce/platform
        storefrontImage: ghcr.io/virtocommerce/storefront
        validateSwagger: 'false'
        installModule: 'true'
        moduleId: ${{ steps.image.outputs.moduleId }}
        
    - name: Newman Action
      uses: matt-ball/newman-action@v1.0.2
      with:
        collection: https://github.com/VirtoCommerce/vc-module-experience-api/blob/collectionfortest/tests/postman/platform_xapi_collection_QA.json
        reporters: json
        enviroment: https://github.com/VirtoCommerce/vc-module-experience-api/blob/collectionfortest/tests/postman/qa.postman_environment.json
        envVar: '[{ "key": "url", "value": "http://localhost:8090" }]'
        delayRequest: 1000
        folder: Ready_for_CI
    - run: npm install -g newman
    - run: newman run https://www.getpostman.com/collections/df0244a9c935884533d6 --folder Ready_for_CI --delay-request 1000
